name: Actions Test-workflow

on: [push]

jobs:
  Test-workflow:
    runs-on: ubuntu-latest
    steps:
      - name: run Actions
        uses: actions/hello-world-javascript-action@v1
        with: 
          who-to-greet: Hello