name: Use of run in steps via Shell Command

on: [push]

jobs:
  Test-workflow:
    runs-on: ubuntu-latest
    steps: 
      - name: Print
        run: echo "How are you?"
      - name: Test multi-line
        run: |
          node -v
          npm -v
      - name: Python Command
        run: |
          import platform
          print(platform.processor())
        shell: python

  Windows-workflow:
    runs-on: windows-latest
    steps: 
      - name: Windows Poweshell
        run: Get-Location
      - name: Directory bash
        run: pwd
        shell: bash